In [ ]:
import pandas as pd
import geopandas as gpd

# Gets the folder directory where urban data is located to avoid duplication
folder = r'D:\Data Analysis\5_Projects\sofia_housing_districts_analysis\data\sofia_data\urbandata_sofia_bg'

# Reads file with district boundaries
district_boundaries = gpd.read_file(folder + r'\natovarv_sasht_polojenie_kk_072020_26_sofpl_20201118.geojson')

# Gets unique districts
district_boundaries['rajon'].unique()

districts = district_boundaries['rajon'].unique()

split_districts = set()
for district in districts:
    if isinstance(district, str):
        split_district = district.split(' / ')
        split_districts.add(split_district[0].strip())

    if len(split_district) == 2:
        split_districts.add(split_district[1].strip())

# A set of unique Sofia Municipality districts in cyrillic
split_districts

{'Банкя',
 'Витоша',
 'Връбница',
 'Възраждане',
 'Изгрев',
 'Илинден',
 'Искър',
 'Красна поляна',
 'Красно село',
 'Кремиковци',
 'Лозенец',
 'Люлин',
 'Младост',
 'Надежда',
 'Нови Искър',
 'Оборище',
 'Овча Купел',
 'Панчарево',
 'Подуене',
 'Сердика',
 'Слатина',
 'Средец',
 'Студентска',
 'Триадица'}

In [34]:
public_transport_accessibility = gpd.read_file(folder + r'\dostup_mgt_all_400_600_800m_overlap_20210300.geojson')

public_transport_accessibility[public_transport_accessibility['name_'].str.contains('СТУДЕНТСКИ')]

,object_id,objectid,facilityid,name_,frombreak,tobreak,id,area_kv_m,geometry
83,145,44665.0,6261.0,БЛ. 60 - СТУДЕНТСКИ ГРАД : 600 - 800,600.0,800.0,b455fef5-0994-4ee0-9136-43cde5f195e1,528580.82,"MULTIPOLYGON (((23.34221 42.64937, 23.3422 42...."
439,2077,46597.0,4971.0,СТУДЕНТСКИ ГРАД : 600 - 800,600.0,800.0,fe15fa7c-f29c-465b-bd8b-4c9b788b72f5,535669.38,"MULTIPOLYGON (((23.3476 42.65295, 23.34813 42...."
1456,4380,48900.0,4971.0,СТУДЕНТСКИ ГРАД : 400 - 600,400.0,600.0,df5f83a3-6918-4625-9931-76c076303643,396186.78,"MULTIPOLYGON (((23.3476 42.65101, 23.34752 42...."
2002,217,44737.0,6213.0,СТУДЕНТСКИ ГРАД : 600 - 800,600.0,800.0,c35344fa-d6ff-4d75-afdd-7660db407eec,520493.22,"MULTIPOLYGON (((23.33667 42.65213, 23.33693 42..."
2164,143,44663.0,6262.0,БЛ. 60 - СТУДЕНТСКИ ГРАД : 600 - 800,600.0,800.0,6bcd4956-707d-47a4-874a-e5d6976f7eb2,531955.64,"MULTIPOLYGON (((23.34176 42.64884, 23.34181 42..."
2168,218,44738.0,6212.0,СТУДЕНТСКИ ГРАД : 600 - 800,600.0,800.0,7b9e4d7f-1fdc-4a5e-bdf9-a3d5a018c88d,490064.11,"MULTIPOLYGON (((23.33295 42.65212, 23.33289 42..."
3703,2075,46595.0,4972.0,СТУДЕНТСКИ ГРАД : 600 - 800,600.0,800.0,d5d251bf-7300-4645-af59-cabeca0d5c63,531581.69,"MULTIPOLYGON (((23.34769 42.65323, 23.34764 42..."
4667,3130,47650.0,6262.0,БЛ. 60 - СТУДЕНТСКИ ГРАД : 400 - 600,400.0,600.0,de7d987f-5a53-4165-8da7-089660ef78e4,340521.42,"MULTIPOLYGON (((23.34042 42.64731, 23.34042 42..."
4670,3132,47652.0,6261.0,БЛ. 60 - СТУДЕНТСКИ ГРАД : 400 - 600,400.0,600.0,c5a78840-5848-4ea0-bff4-c986810bbace,364012.75,"MULTIPOLYGON (((23.34273 42.64742, 23.34274 42..."
4791,3277,47797.0,6213.0,СТУДЕНТСКИ ГРАД : 400 - 600,400.0,600.0,594965df-73ad-433d-9786-cc73b0b38e88,379214.07,"MULTIPOLYGON (((23.33636 42.65054, 23.33701 42..."
4794,3281,47801.0,6212.0,СТУДЕНТСКИ ГРАД : 400 - 600,400.0,600.0,b28076bd-7006-467f-a3c8-5b0442db0ab5,387866.43,"MULTIPOLYGON (((23.33346 42.65035, 23.33365 42..."
5547,4383,48903.0,4972.0,СТУДЕНТСКИ ГРАД : 400 - 600,400.0,600.0,78ea0b12-8f4b-4e6e-a4a4-82a8138815d4,403517.92,"MULTIPOLYGON (((23.34773 42.65128, 23.34783 42..."
7330,7000,51520.0,4972.0,СТУДЕНТСКИ ГРАД : 0 - 400,0.0,400.0,a0e78e5d-058a-4155-ac08-d29af9f22e74,243521.13,"MULTIPOLYGON (((23.3471 42.6496, 23.34694 42.6..."
7335,7005,51525.0,4971.0,СТУДЕНТСКИ ГРАД : 0 - 400,0.0,400.0,b1da63b2-feca-484f-881e-273141b915c3,230668.08,"MULTIPOLYGON (((23.34679 42.64941, 23.34667 42..."
8229,8105,52625.0,6213.0,СТУДЕНТСКИ ГРАД : 0 - 400,0.0,400.0,ab5e6d89-d2e7-462f-86a5-0145e55e94d7,233709.54,"MULTIPOLYGON (((23.33615 42.64887, 23.33664 42..."
8240,8102,52622.0,6212.0,СТУДЕНТСКИ ГРАД : 0 - 400,0.0,400.0,1acfe13f-7489-4137-abe5-b95f461fe071,251494.40,"MULTIPOLYGON (((23.33445 42.64853, 23.33444 42..."
8339,8249,52769.0,6261.0,БЛ. 60 - СТУДЕНТСКИ ГРАД : 0 - 400,0.0,400.0,af31b61b-dfb7-4927-8c48-a012a34166aa,275240.84,"MULTIPOLYGON (((23.34218 42.64613, 23.34221 42..."
8340,8252,52772.0,6262.0,БЛ. 60 - СТУДЕНТСКИ ГРАД : 0 - 400,0.0,400.0,b1105afb-4549-4c09-8c6e-16818f0264f5,264875.52,"MULTIPOLYGON (((23.34046 42.64587, 23.34046 42..."

In [38]:
schools_accessibility = gpd.read_file(folder + r'\uchilishta_points_26_sofpr_20180808.geojson')

schools_accessibility.head()

,id,object_nam,object_nom,kod_rayon,adres,finansiran,type,detaili,zabelezhka,br_paralel,kodadmin,geometry
0,1,Национално училище за танцово изкуство,NaN,07,бул. Шипченски проход №48,1,4,http://89.252.196.217/Schools/search,NaN,0.0,2902301,MULTIPOINT ((23.36594 42.67788))
1,2,22 СОУ Георги С. Раковски,22.0,10,бул. Витоша №132,2,3,http://89.252.196.217/Schools/search,NaN,55.0,2224022,MULTIPOINT ((23.31459 42.68476))
2,3,"1-во помощно училище ""ПРОФ. ДПН Г. АНГУШЕВ"" (Ц...",NaN,12,бул. Тодор Александров №175,1,6,http://89.252.196.217/Schools/search,Център за специална образователна подкрепа (ЦСОП,0.0,0,MULTIPOINT ((23.29248 42.70397))
3,4,Национална природо-математическа гимназия Акад...,NaN,09,"ж.к. Лозенец, ул. Бигла №52",1,4,http://89.252.196.217/Schools/search,NaN,40.0,2211304,MULTIPOINT ((23.33011 42.67053))
4,5,21 СОУ Христо Ботев,21.0,09,"ж.к. Лозенец, ул. Люботрън №12",2,3,http://89.252.196.217/Schools/search,NaN,33.0,2211021,MULTIPOINT ((23.31546 42.66941))