In [2]:
"""
Imports variables from urban_data_variables module.
Replaces 'obns_lat' from district_codes with the correct latin spelling.
"""

import pandas as pd
import geopandas as gpd
import re
from urban_data_variables import (
    districts,
    district_codes,
    schools,
    kindergartens,
    parking_spaces,
    public_transport_accessibility,
    parks_accessibility,
    healthcare_coverage
)
pd.set_option('display.max_rows', None)

In [3]:
import cyrtranslit

# Applies a lambda function to latinize district names
district_codes['obns_lat'] = district_codes['obns_cyr'].apply(lambda x: cyrtranslit.to_latin(x, 'bg'))
# Removes diacritical A
district_codes['obns_lat'] = district_codes['obns_lat'].apply(lambda x: x.replace('Ă', 'A'))
district_codes

,id,obns_num,obns_cyr,obns_lat,geometry
0,3,09,ЛОЗЕНЕЦ,LOZENETS,"MULTIPOLYGON (((23.3095 42.67248, 23.31027 42...."
1,4,10,ТРИАДИЦА,TRIADITSA,"MULTIPOLYGON (((23.28299 42.65376, 23.28319 42..."
2,5,17,ВИТОША,VITOSHA,"MULTIPOLYGON (((23.13931 42.59156, 23.13938 42..."
3,6,23,ПАНЧАРЕВО,PANCHAREVO,"MULTIPOLYGON (((23.28519 42.55851, 23.2853 42...."
4,7,18,ОВЧА КУПЕЛ,OVCHA KUPEL,"MULTIPOLYGON (((23.13952 42.6773, 23.13957 42...."
5,8,11,КРАСНА ПОЛЯНА,KRASNA POLYANA,"MULTIPOLYGON (((23.23027 42.69073, 23.23028 42..."
6,9,05,СЕРДИКА,SERDIKA,"MULTIPOLYGON (((23.29775 42.71481, 23.29794 42..."
7,11,13,НАДЕЖДА,NADEZHDA,"MULTIPOLYGON (((23.27909 42.76763, 23.27959 42..."
8,12,21,НОВИ ИСКЪР,NOVI ISKAR,"MULTIPOLYGON (((23.24235 42.81768, 23.24238 42..."
9,13,20,ВРЪБНИЦА,VRABNITSA,"MULTIPOLYGON (((23.20036 42.7711, 23.20041 42...."
10,14,19,ЛЮЛИН,LYULIN,"MULTIPOLYGON (((23.19509 42.69874, 23.19556 42..."
11,15,24,БАНКЯ,BANKYA,"MULTIPOLYGON (((23.05108 42.70209, 23.05111 42..."
12,19,07,СЛАТИНА,SLATINA,"MULTIPOLYGON (((23.34754 42.68339, 23.34764 42..."
13,20,14,ИСКЪР,ISKAR,"MULTIPOLYGON (((23.4421 42.69014, 23.44094 42...."
14,21,15,МЛАДОСТ,MLADOST,"MULTIPOLYGON (((23.38711 42.66584, 23.38755 42..."
15,22,22,КРЕМИКОВЦИ,KREMIKOVTSI,"MULTIPOLYGON (((23.50934 42.86418, 23.50944 42..."
16,23,06,ПОДУЯНЕ,PODUYANE,"MULTIPOLYGON (((23.36513 42.7222, 23.36528 42...."
17,1,01,СРЕДЕЦ,SREDETS,"MULTIPOLYGON (((23.31899 42.68899, 23.31903 42..."
18,2,08,ИЗГРЕВ,IZGREV,"MULTIPOLYGON (((23.33613 42.67262, 23.33794 42..."
19,10,12,ИЛИНДЕН,ILINDEN,"MULTIPOLYGON (((23.27263 42.71003, 23.27273 42..."
20,16,02,КРАСНО СЕЛО,KRASNO SELO,"MULTIPOLYGON (((23.26913 42.67422, 23.26919 42..."
21,17,03,ВЪЗРАЖДАНЕ,VAZRAZHDANE,"MULTIPOLYGON (((23.28702 42.68995, 23.28714 42..."
22,18,04,ОБОРИЩЕ,OBORISHTE,"MULTIPOLYGON (((23.32176 42.69771, 23.32181 42..."
23,24,16,СТУДЕНТСКИ,STUDENTSKI,"MULTIPOLYGON (((23.36859 42.66832, 23.36885 42..."

In [4]:
neighborhoods_list = districts['regname'].tolist()
neighborhoods_list = [cyrtranslit.to_latin(n, 'bg') for n in neighborhoods_list]
neighborhoods_list = [n.replace('Ă', 'A').replace('ă', 'a') for n in neighborhoods_list]

# Split several names into different entries
neighborhoods_list = sorted({part.strip() for n in neighborhoods_list for part in re.split(r',', n) if part.strip()})

# Remove small words
neighborhoods_list = [re.sub(r'\b\w{1,2}\.', '', n) for n in neighborhoods_list]
neighborhoods_list = [n.strip() for n in neighborhoods_list]

def tidy(n):
    n = re.sub(r'\s*-\s*(\d+)\s*mr\b', r' \1', n, flags=re.IGNORECASE)  # "Lyulin - 10 mr" -> "Lyulin 10"
    return re.sub(r'\s+', ' ', n).strip()

neighborhoods_list = sorted({tidy(n) for n in neighborhoods_list})

neighborhoods_list

['"SHTetnitsa"',
 '1',
 '3-ta izvangradska chast',
 'Abdovitsa',
 'Avramitsa"',
 'BAN 4km',
 'Balsha',
 'Balsha - razshirenie',
 'Balsha poleto',
 'Bankya',
 'Bankya - Verdikal',
 'Bankya - razshirenie',
 'Bardo - Dimitar',
 'Barite',
 'Batareya',
 'Bel Kamak',
 'Beli Breg - Grobishtata',
 'Beli Brezi',
 'Beli rid',
 'Belikata',
 'Belovodski pat',
 'Benkovski',
 'Benkovski - razshirenie',
 'Berilitsa',
 'Bistritsa',
 'Bistritsa - Kalfin dol',
 'Bistritsa - Kokalyane - pole',
 'Bistritsa - SHiranata',
 'Bistritsa - TSonkina mahala',
 'Bistritsa - razsh. TSonkina mahala',
 'Bistritsa - razsh. iztok',
 'Bistritsa - rezervata',
 'Bitpazar Malashevtsi',
 'Bivolyarnik',
 'Bivshi kazarmi GUSV Smardan',
 'Biznes zona Progono',
 'Biznes zona bul. Iztochna tangenta - Vrazhdebna',
 'Blatata Krivina',
 'Bogrov',
 'Bogrovski pesotsi',
 'Borisova gradina - Loven park',
 'Borisova gradina - Pogrebite chast 1',
 'Borisova gradina - Seminariyata',
 'Borisova gradina - sever',
 'Borisova gradina - yug',
 'Borovo',
 'Botunets',
 'Boyana',
 'Boyanski grobishta',
 'Branchovitsa',
 'Branishko loze',
 'Bresto',
 'Brodo',
 'Buhovo',
 'Bunkera',
 'Busmantsi',
 'CHagovo raske',
 'CHaushitsa',
 'CHelopechene',
 'CHelopechene - Zavoya',
 'CHelopechene - Zavoya zem. zemya',
 'CHelopechensko ezero - Balastriera',
 'CHepinsko pole',
 'CHepintsi',
 'CHepintsi - Kraveferma D-r Pashov',
 'CHepintsi - razshirenie',
 'CHerniya kos',
 'CHiprovitsa',
 'CHolanitsa - CHetarlaka',
 'CHovkarniko',
 'CHubra',
 'CHuchulitsa',
 'CHuchulitsa - sever',
 'CHuchulitsa - yug',
 'CHuchulitsa - zapad',
 'Dalgata stran',
 'Darnjov kamak i Podlozishte',
 'Darvenitsa',
 'Detski grad',
 'Devo most',
 'Dianabad',
 'Dimitar Milenkov',
 'Dobroslavtsi',
 'Dobroslavtsi - letishte',
 'Dobroslavtsi poleto',
 'Dolni Bogrov',
 'Dolni Bogrov - sever',
 'Dolni Lozen',
 'Dolni Lozen - BCHK',
 'Dolni Pasarel',
 'Dolo',
 'Dragalevtsi',
 'Dragalevtsi - razshirenie - sever',
 'Druzhba 1 - iztok',
 'Druzhba 1 - zapad',
 'Druzhba 2 - iztok',
 'Druzhba 2 - zapad',
 'Dupkite',
 'Dzukata',
 'Elata - Kosharite',
 'Fakulteta',
 'Filipovtsi',
 'Fondovi zhilishta',
 'Gaber',
 'Gabera',
 'Gara Pioner',
 'Gardova glava',
 'Geo Milev',
 'Gerena',
 'German',
 'Gevgeliyski',
 'Gjolovete',
 'Gladno pole',
 'Gnilyane',
 'Goli del',
 'Golyamata lokva',
 'Golyamata lokva - targovski park 2',
 'Gorna Banya - Domuz dere',
 'Gorna Banya - ZHP gara',
 'Gorna Banya 2; Golema Mogila',
 'Gorna banya',
 'Gorna banya (razsh. yug na Gorna banya)',
 'Gorna banya - razsh. Lozishte Podlozishte',
 'Gorni Bogrov',
 'Gorublyane',
 'Gorublyane 2 i 3',
 'Gotse Delchev',
 'Gradishte',
 'Gradoman',
 'Gradoman - razshirenie',
 'Gradomanski pat',
 'Grobishten park Malashevtsi',
 'Gurmazitsa',
 'Hadzhi Dimitar',
 'Han Bogrov - PZ',
 'Hidropark Iskar - CHepintsi',
 'Hidropark Iskar - Gorublyane',
 'Hidropark Iskar - Kamping Vrana',
 'Hidropark Iskar - Kazichene',
 'Hidropark Iskar - Kubratovo - Novi Iskar',
 'Hidropark Iskar - Novi Iskar',
 'Hidropark Iskar - Vododayna zona yaz. Iskar',
 'Hidropark Iskar - chast German',
 'Hidropark Iskar - chast Letishte sever',
 'Hidropark Iskar - chast NPZ Iskar sever',
 'Hidropark Iskar - chast Novi Iskar',
 'Hidropark Iskar - chast Pasarel - Pancharevo',
 'Hidropark Iskar - chast Vrazhdebna',
 'Hidropark Iskar - chast Vrazhdebna - Kubratovo',
 'Hidropark Iskar - defileto',
 'Hipodruma',
 'Hladilnika',
 'Hristo Botev',
 'Hristo Smirnenski',
 'Hvostohranilishte Bogrov - Lakata',
 'Hvostohranilishte Buhovo',
 'Hvostohranilishte CHelopechene',
 'Ilinden',
 'Iliyantsi',
 'Iliyantsi - man. Iliya',
 'Ivan Vazov',
 'Ivanyane',
 'Ivanyane poleto',
 'Izgrev',
 'Iztochen Park Mladost',
 'Iztok - iztok',
 'Kakini padini - YAzovir',
 'Kamen rid',
 'Kapina',
 'Kariera Rudinata',
 'Karo',
 'Karpuzitsa - iztok',
 'Karpuzitsa - zapad',
 'Katina',
 'Katina - razshirenie',
 'Kazichene',
 'Kazichene - yug',
 'Kelkaza',
 'Kelkaza - Mramor',
 'Kiliite',
 'Kinotsentar chast 3',
 'Kinotsentara. Gabaro - Azmata',
 'Klisura',
 'Klyunchov rid',
 'Knyazheska gradina',
 'Knyazhevo',
 'Knyazhevska gora',
 'Kokalyane',
 'Kokalyane - Bachol',
 'Koriya',
 'Kosanin dol',
 'Kosharite',
 'Kovachki koshari',
 'Kraishte',
 'Krasna polyana - chast 1 i 2',
 'Krasna polyana - chast 3',
 'Krasno selo',
 'Krasta',
 'Krastova vada - iztok',
 'Krastova vada - zapad',
 'Kremikovtsi',
 'Kriva reka',
 'Krivina',
 'Krushi',
 'Krushovets',
 'Kubratovo',
 'Kubratovsko pole',
 'Lagatar',
 'Lagera',
 'Lakata',
 'Laska',
 'Lavandulite',
 'Lednik',
 'Lenishtata',
 'Letishten k-s Sofiya',
 'Lev Tolstoy',
 'Levski - zona G',
 'Levski - zona V',
 'Limonkjovitsa',
 'Livadeto',
 'Lokorsko',
 'Lokorsko 1',
 'Lokva',
 'Lokvata',
 'Lozen',
 'Lozenets chast 1',
 'Lozenets chast 2 - sever',
 'Lozenets chast 2 i 3 - yug',
 'Lozenets chast 3',
 'Lozenska planina',
 'Lyulin',
 'Lyulin - razshirenie - yug',
 'Lyulin - razshirenie - zapad',
 'Lyulin - tsentar',
 'Lyulin 1',
 'Lyulin 10',
 'Lyulin 2',
 'Lyulin 3',
 'Lyulin 4',
 'Lyulin 5',
 'Lyulin 6',
 'Lyulin 7',
 'Lyulin 8',
 'Lyulin 9',
 'Lyulin planina - iztok',
 'Lyulin planina - zapad',
 'Makazitsa',
 'Malinova dolina - gerena',
 'Malinova dolina - iztok',
 'Malinova dolina - zapad',
 'Malo Buchino',
 'Manastir Iliya',
 'Manastirishte',
 'Manastirski livadi - iztok',
 'Manastirskoto',
 'Manchov valog',
 'Manilov dol',
 'Manish',
 'Marchaevo',
 'Marinova polyana',
 'Martvako',
 'Meditsinski tsentar Suhodol',
 'Merata',
 'Mihaylovo',
 'Miramonte',
 'Mirovyane',
 'Mirovyane - razshirenie',
 'Mirovyane poleto',
 'Mladost 1',
 'Mladost 1A',
 'Mladost 2',
 'Mladost 3',
 'Mladost 4',
 'Mladost 4 Kambanite - Amerikanski kolezh',
 'Moderno predgradie',
 'Mogilata',
 'Morozhina',
 'Mramor',
 'Mramor - zem. zemi',
 'Mramor i PSZ',
 'Musagenitsa',
 'Mutiyska vodenitsa',
 'NDK - ploshtad Balgariya',
 'NPZ Hadzhi Dimitar',
 'NPZ Hadzhi Dimitar - Malashevtsi 1',
 'NPZ Hadzhi Dimitar - Malashevtsi 2',
 'NPZ Hladilnika',
 'NPZ Iliyantsi - iztok',
 'NPZ Iliyantsi - sever',
 'NPZ Iliyantsi - zapad',
 'NPZ Iskar - sever',
 'NPZ Iskar - yug',
 'NPZ Iztok',
 'NPZ Iztok - podzona Gorublyane',
 'NPZ Kremikovtsi',
 'NPZ Orion',
 'NPZ Sredets 1',
 'NPZ Sredets 2',
 'NPZ Voenna rampa - iztok',
 'NPZ Voenna rampa - zapad',
 'NPZ Zaharna fabrika',
 'Nadezhda 1',
 'Nadezhda 2',
 'Nadezhda 3',
 'Nadezhda 4',
 'Natsionalen Kinotsentar Sofiya - Boyana',
 'Negovan',
 'Novi Iskar',
 'Novi Iskar - Gnilyane',
 'Novi Iskar - Izgrev',
 'Novi Iskar - Katina poleto',
 'Novi Iskar - Kumaritsa',
 'Novi Iskar - Kurilo',
 'Novi Iskar - Slavovtsi',
 'Novi Iskar - Slavovtsi - razshirenie',
 'Obelya',
 'Obelya 1',
 'Obelya 2',
 'Obradovski geren',
 'Oreshkovitsa',
 'Orlandovtsi',
 'Orlandovtsi - Malashevtsi',
 'Orlova krusha',
 'Ormana',
 'Otvad rekata',
 'Ovcha Kupel',
 'Ovcha Kupel - 1',
 'Ovcha Kupel - 50',
 'Ovcha Kupel - sever',
 'Ovcha Kupel - yug',
 'Ozelenyavane transp. vazel Severna - iztochna tangenti',
 'PV Nadezhda',
 'PZ Kazichene - zapad / Vidnite',
 'PZ Zadgarov - TETS Sofiya',
 'Padarski kolibi',
 'Padinata',
 'Pancharevo',
 'Pancharevo - CHereshovi gradini iztok',
 'Park - Borisova gradina - razsh. Krastova vada',
 'Park - muzey Vrana',
 'Park Benkovski - zapad',
 'Park Botanicheska gradina',
 'Park Bratska Mogila',
 'Park Geo Milev',
 'Park Kambanite - r-n Pancharevo',
 'Park Kambanite - r-n Vitosha',
 'Park Levski G - sever',
 'Park Nadezhda',
 'Park Studentski',
 'Park Vartopo - sever',
 'Park Vartopo - yug',
 'Park Vitosha zastroeni zemi ZHeleznitsa',
 'Park Vrazhdebna - sever',
 'Pasarel',
 'Pavlovo - Bakston',
 'Petka',
 'Pladnishte',
 'Plana',
 'Plana planina',
 'Planina Vitosha - r-n Pancharevo',
 'Planina Vitosha - r-n Vitosha',
 'Planinski gledki',
 'Podgumer',
 'Podgumer - Pyasachni karieri',
 'Podgumerski manastir Sveti Dimitar',
 'Poduyane',
 'Poduyane - TSentar',
 'Poleto',
 'Poleto 2',
 'Popov dol',
 'Pozharo',
 'Prechistvatelna stantsiya Kubratovo',
 'Presveta',
 'Prez Iskar',
 'Primichur',
 'Priplat',
 'Progon',
 'Radevi krushi',
 'Radova mahala',
 'Ranova niva',
 'Rasul',
 'Ravnishte',
 'Razdoltsi',
 'Razpake',
 'Razsadnik Malo Buchino',
 'Razsadnika - Konjovitsa',
 'Republika',
 'Republika - Toleva mahala',
 'Rezidentsiya Boyana',
 'Rido',
 'Romcha',
 'Rudnik Kremikovtsi',
 'Rudnik Kremikovtsi 2',
 'Rusiya',
 'SHTarkelovo gnezdo',
 'SHamaka',
 'SHavarna bara',
 'SHeovitsa',
 'SHlakohranilishte Kremikovtsi',
 'SHlyapovi koshari - sever',
 'SHlyapovi koshari - yug',
 'SOP Kazichene - Krivina',
 'SOP Lozen Ikonomicheska zona - sever',
 'SOP Lozen Ikonomicheska zona - yug',
 'SOP NPZ Kazichene',
 'SOP sever - Sevladitsa',
 'SPZ Moderno predgradie - razshirenie 1',
 'SPZ Moderno predgradie - razshirenie 2',
 'SPZ Novi Iskar - Kurilo',
 'SPZ Slatina - yug 1',
 'SPZ Slatina - yug 2',
 'SSZ CHepintsi',
 'SZ Birimirtsi-Broda',
 'Sadinata',
 'Sekulitsa',
 'Selishtata',
 'Serdika',
 'Seslavtsi',
 'Severen park',
 'Severen park - Bakarena fabrika',
 'Severen park chast 2',
 'Simeonovo',
 'Skladova zona Iliyantsi - Vrabnitsa',
 'Slaviya',
 'Smiljovitsa',
 'Sofiya - vilidzh',
 'Sofiyska planina (zapadna Stara planina) 1',
 'Sofiyska planina (zapadna Stara planina) 2',
 'Sofiyski tsentralni grobishta',
 'Sofiysko pole Kazichene - yug',
 'Srabski azmak',
 'Sredni del',
 'Sredoreka',
 'Starata Koriya',
 'Stariyat most',
 'Stefan Karadzha',
 'Strelbishte',
 'Studentski grad - sever',
 'Studentski grad - yug',
 'Studentski grad - zapad',
 'Suhata reka - iztok',
 'Suhata reka - sever',
 'Suhata reka - zapad',
 'Suhodol',
 'Sveta Troitsa',
 'Svetovrachane',
 'Svetovrachene',
 'Svetovrachene - razshirenie',
 'Svetovrachene NPZ',
 'Svoboda',
 'TSGCH Bukata',
 'TSGCH Evreyski grobishta',
 'TSGCH Zona A - iztok',
 'TSGCH Zona A - sever',
 'TSGCH Zona A - yug',
 'TSGCH Zona B18+',
 'TSGCH Zona B19+',
 'TSGCH Zona B2-3+',
 'TSGCH Zona B3+',
 'TSGCH Zona B4+',
 'TSGCH Zona B5+',
 'TSGCH Zona B5-3+',
 'TSGCH Zona B5-A',
 'TSGCH Zona G11 - iztok',
 'TSGCH Zona G12 - sever',
 'TSGCH Zona G12 - yug',
 'TSGCH Zona G13',
 'TSGCH Zona G14 - iztok',
 'TSGCH Zona G14 - zapad',
 'TSGCH Zona G6 - iztok',
 'TSGCH Zona G6 - zapad',
 'TSGCH Zona G8',
 'TSGCH Zona G8 - Sredets',
 'TSGCH Zona G8 chast Triaditsa',
 'TSGCH Zona TSentralna gara',
 'TSGCH Zona V15',
 'TSGCH Zona V17 - 16 s Predgarov ploshtad',
 'TSGCH Zona V17 - Banishora',
 'TSGCH Zoni B2 1 i 2',
 'TSGCH Zoni G10 i chast ot A',
 'TSarna bara',
 'TSarnokos',
 'TSelinite',
 'TSiganski grobishta',
 'Tarnitsata',
 'Tatare',
 'Tatarski brod',
 'Terasite',
 'Teritorii',
 'Toleva mahala',
 'Trebich',
 'Trebich zem. zemya',
 'Triagalnika - Nadezhda',
 'Turchenitsa',
 'Umni dol',
 'Vasil Levski - sever',
 'Vasil Levski - yug',
 'Verdikal',
 'Verdikal - zemlishte pole',
 'Virovete',
 'Viso',
 'Vitosha - Lozenets',
 'Vitosha - VETS Simeonovo',
 'Vladaya',
 'Vlashka reka',
 'Vodenitsata',
 'Voluyak',
 'Voluyak - ZHP gara Voluyak',
 'Voynegovtsi',
 'Voynegovtsi - razshirenie',
 'Voyskovi rayon Gorna Banya',
 'Vrabnitsa 1A',
 'Vrabnitsa 1B',
 'Vrabnitsa 2A',
 'Vrabnitsa 2B',
 'Vrana',
 'Vrana - Lozen - Triagalnika',
 'Vrana - stopanstvoto',
 'Vrana-German',
 'Vranyaka',
 'Vrazhdebna',
 'Vrazhdebna - yug',
 'YAna',
 'YAna i ZHelyava',
 'YAnino raske',
 'YApadzha',
 'YAvorov',
 'YAzovir Iskar',
 'YUzhen park',
 'YUzhen park chast 2',
 'YUzhen park chast 3',
 'ZHP Areal - Poduyane (chast 1)',
 'ZHP Areal - Poduyane (chast 2)',
 'ZHP Areal - Poduyane (chast 3)',
 'ZHP Areal - TSentralna gara',
 'ZHP Areal Nadezhda - Zaharna fabrika',
 'ZHeleznitsa',
 'ZHeleznitsa - mahala CHemernik i TSarevi koshari',
 'ZHelyava',
 'ZHiten',
 'ZHiten poleto',
 'Zapaden park',
 'Zapaden park - razsh. Golyama Konjovitsa',
 'Zapaden park - razsh. Malka Konjovitsa 1',
 'Zapaden park - razsh. Malka Konjovitsa 2',
 'Zatvor Kremikovtsi',
 'Zem. zemi mezhdu Benkovski i CHepinsko',
 'Zona za otdih Pancharevo - plazha',
 'Zona za otdih SHishmanovski manastir',
 'Zoopark',
 'Zvezdana (TSarkvishte)',
 'bul. 9-ti Septemvri',
 'bul. Lomsko shose',
 'bul. TSarigradsko 7-11km - sever',
 'bul. TSarigradsko 7-11km - yug (HMS BAN)',
 'i Bogrov pole yug',
 'i Ivanyane',
 'k-s Meditsinska akademiya',
 'obsl. zona Okolovrasten pat - Malinov yug',
 'prilezhashti na paten vazel Okolovrasten pat - bul. Slivnitsa',
 'r-n Bankya zemlishte',
 'stopanski dvor',
 'zem. zemi - Bogrov',
 'zem. zemi - Podgumer',
 'zem. zemi Busmantsi - Vrazhdebna',
 'zem. zemi Malashevtsi Gerena',
 'zem. zemi r-n Kremikovtsi',
 'zhk. Manastirski livadi - zapad',
 'zona za otdih Izvora']

In [5]:
"""
Mapping districts and neighborhoods to the scraped listings files
"""

sofia_for_rent_scraped = pd.read_csv(r'D:\Data Analysis\5_Projects\sofia_housing_districts_analysis\data\housing_listings_scraped\sofia_for_rent_scraped.csv')

districts_list = district_codes['obns_lat'].tolist()

pattern_districts = '|'.join(re.escape(d) for d in sorted(districts_list, key=len, reverse=True))
pattern_neighborhoods = '|'.join(re.escape(d) for d in sorted(neighborhoods_list, key=len, reverse=True))

sofia_for_rent_scraped['district'] = sofia_for_rent_scraped['location'].str.extract(rf'\b({pattern_districts})\b', flags=re.IGNORECASE)[0]
sofia_for_rent_scraped['neighborhood'] = sofia_for_rent_scraped['location'].str.extract(rf'\b({pattern_neighborhoods})\b', flags=re.IGNORECASE)[0]

# match rate
len(sofia_for_rent_scraped[(sofia_for_rent_scraped['neighborhood'].notna()) | (sofia_for_rent_scraped['district'].notna())]) / len(sofia_for_rent_scraped)

0.5711145096539858

In [6]:
sofia_for_sale_scraped = pd.read_csv(r'D:\Data Analysis\5_Projects\sofia_housing_districts_analysis\data\housing_listings_scraped\sofia_for_sale_scraped.csv')

sofia_for_sale_scraped['district'] = sofia_for_sale_scraped['location'].str.extract(rf'\b({pattern_districts})\b', flags=re.IGNORECASE)[0]
sofia_for_sale_scraped['neighborhood'] = sofia_for_sale_scraped['location'].str.extract(rf'\b({pattern_neighborhoods})\b', flags=re.IGNORECASE)[0]

# match rate
len(sofia_for_sale_scraped[(sofia_for_rent_scraped['neighborhood'].notna()) | (sofia_for_sale_scraped['district'].notna())]) / len(sofia_for_rent_scraped)

0.6298030969221946

In [7]:
to_remove = ['Sofia,', 's.', 'v.z.', 'zh.gr.', 'zh.k.', 'm.', 'kv.', 'm-t']

def clean_neighborhood(name):
    name = cyrtranslit.to_latin(name, 'bg').replace('Ă', 'A').replace('ă', 'a')
    for r in to_remove:
        name = name.replace(r, '')
    name = (name.replace('"', '')
            .replace('Belite', 'Beli')
            .replace('Botunets 2', 'Botunets')
            .replace('3 chast', '')
            .replace('.  Gabaro - Azmata', '')
            .replace('Krasna polyana 1', 'Krasna polyana 1/2')
            .replace('Krasna polyana 2', 'Krasna polyana 1/2')
            .replace('Krasna polyana - chast 3', 'Krasna polyana 3')
            .replace('Krasna polyana - chast 1 i 2', 'Krasna polyana 1/2')
            .replace('Levski V', 'Levski')
            .replace('Ovcha Kupel - 1', 'Ovcha Kupel 1')
            .replace('Ovcha kupel 2', 'Ovcha kupel')
            .replace('Ovcha Kupel - yug', 'Ovcha Kupel')
            .replace('Ovcha Kupel - sever', 'Ovcha Kupel')
            .replace('Ovcha Kupel -  50', 'Ovcha Kupel')
            .replace('Republika 2', 'Republika')
            .replace('Vitosha - VETS Simeonovo', 'Simeonovo')
            .replace('Dragalevtsi - razshirenie - sever', 'Dragalevtsi')
            .replace('Dragalevtsi, v. Miramonte', 'Dragalevtsi')
            .strip())
    name = re.sub(r'^(Simeonovo|Dragalevtsi)$', 'Simeonovo - Dragalevtsi', name)
    name = re.sub(r'^.*Vrana.*$', 'Vrana', name)
    name = re.sub(r'^.*German.*$', 'German', name)
    name = re.sub(r'^(Vrana|German)$', 'Vrana - German', name)
    return re.sub(r'\s*-\s*(\d+)\s*mr\b', r' \1', name).lower()

In [24]:
combined_listings = pd.concat([sofia_for_sale_scraped, sofia_for_rent_scraped], ignore_index=True)

combined_listings['location_clean'] = combined_listings['location'].apply(clean_neighborhood)

combined_listings.sample(5)

,url,ad_id,listing_type,location,price_eur,area_sqm,price_per_sqm_eur,floor,central_heating,gas,...,description_bulgarian,features,views,saves,ad_published_date,agency,date_scraped,district,neighborhood,location_clean
9636,https://imoti.info/en/properties/83852432-for-...,83852432,2 bedroom,"Sofia, Lyulin - tsentar",271 220,135,"2 009,04",3rd,NO,NO,...,Агенция SUPRIMMO: www.suprimmo.bg\nПредставяме...,"[""Lift""]",1191,1,12 July 2026,SUPRIMMO - GLAVEN OFIS,2026-09-25 18:39:02,Lyulin,Lyulin - tsentar,lyulin - tsentar
34593,https://imoti.info/en/properties/51908257-for-...,51908257,2 bedroom,"Sofia, Tsentar",990,90,11,3rd,LOCAL HEATING,-,...,Ел-Ем предлага стилно обзавден 3-стаен апартам...,"[""Furnished"", ""Security"", ""Air-condition"", ""Ac...",482,1,15 September 2026,AGENTSIYA EL-EM EOOD,2026-09-25 16:26:14,NaN,NaN,tsentar
9369,https://imoti.info/en/properties/95551979-for-...,95551979,2 bedroom,"Sofia, Lozenets",660 000,156,"4 230,77",5th,LOCAL HEATING,-,...,"Топ локация, 600 метра от НДК, до градина 'Бан...","[""Lift"", ""With a garage"", ""With a parking lot""...",891,0,1 September 2026,ESTEYT MARK,2026-09-25 18:36:20,Lozenets,NaN,lozenets
14280,https://imoti.info/en/properties/38555958-for-...,38555958,3 bedroom,"Sofia, Manastirski livadi",391 300,170,"2 301,76",3rd,-,-,...,Предлагаме за продажба просторен и светъл апар...,"[""Lift"", ""With a garage"", ""With a parking lot""]",382,0,8 September 2026,ALDES IMOTI,2026-09-25 19:24:33,NaN,NaN,manastirski livadi
9222,https://imoti.info/en/properties/11552698-for-...,11552698,1 bedroom,"Sofia, Lozenets",415 000,82,"5 060,98",2nd,YES,NaN,...,BULGARIA SOTHEBY’S INTERNATIONAL REALTY има уд...,"[""Lift"", ""Security cameras"", ""Access control"",...",59,0,Обявата е коригирана на 10 September 2026,BALGARIYA SOTBIS INTERNESHANAL RIALTI,2026-09-25 18:34:51,Lozenets,NaN,lozenets

In [9]:
districts['regname_clean'] = districts['regname'].apply(clean_neighborhood)

districts[districts['regname_clean'].str.contains('b-5', case=False)]

Empty GeoDataFrame
Columns: [object_id, regname, rajon, area_sos500, rzp_jilsgr, rzp_all, redukcia_20%, ppl_30kvm, ppl_35kvm, ppl_40kvm, area_ge, dens30_ppl_kvkm, dens35_ppl_kvkm, dens40_ppl_kvkm, id, area_kv_m, geometry, regname_clean]
Index: []

In [27]:
regname_clean_set = {s.strip().lower() for s in districts['regname_clean'].dropna()}         
location_clean_set = {s.strip().lower() for s in combined_listings['location_clean'].dropna()} 

matches = {x: [y for y in regname_clean_set if x in y] for x in location_clean_set}

matched = {x: ys for x, ys in matches.items() if ys}
unmatched = {x for x, ys in matches.items() if not ys}

unmatched

{'7-mi 11-ti kilometar',
 'doktorski pametnik',
 'eksperimentalen',
 'oborishte',
 'poligona',
 'reduta',
 'zona b-18',
 'zona b-19',
 'zona b-5',
 'zona b-5-3'}

In [11]:
districts['regname_clean_2'] = districts['regname_clean'].apply(
    lambda r: max([x for x in location_clean_set if x in r], key=len, default=None)
    if isinstance(r, str) else None
)

In [12]:
lookup = (
    districts
    .dropna(subset=['regname_clean_2'])
    .assign(exact=lambda d: d['regname_clean'].str.strip().str.lower() == d['regname_clean_2'])
    .sort_values('exact', ascending=False)
    .drop_duplicates('regname_clean_2')
    .drop(columns='exact')
)

merge = combined_listings.merge(
    lookup, how='left',
    left_on='location_clean', right_on='regname_clean_2',
    validate='m:1'
)

merge.columns

Index(['url', 'ad_id', 'listing_type', 'location', 'price_eur', 'area_sqm',
       'price_per_sqm_eur', 'floor', 'central_heating', 'gas',
       'construction_type', 'construction_year', 'description_bulgarian',
       'features', 'views', 'saves', 'ad_published_date', 'agency',
       'date_scraped', 'district', 'neighborhood', 'location_clean',
       'object_id', 'regname', 'rajon', 'area_sos500', 'rzp_jilsgr', 'rzp_all',
       'redukcia_20%', 'ppl_30kvm', 'ppl_35kvm', 'ppl_40kvm', 'area_ge',
       'dens30_ppl_kvkm', 'dens35_ppl_kvkm', 'dens40_ppl_kvkm', 'id',
       'area_kv_m', 'geometry', 'regname_clean', 'regname_clean_2'],
      dtype='str')

In [43]:
districts[districts['rajon'].str.contains('Ц', case=False)]

,object_id,regname,rajon,area_sos500,rzp_jilsgr,rzp_all,redukcia_20%,ppl_30kvm,ppl_35kvm,ppl_40kvm,area_ge,dens30_ppl_kvkm,dens35_ppl_kvkm,dens40_ppl_kvkm,id,area_kv_m,geometry,regname_clean,regname_clean_2
12,108,Рудник Кремиковци 2,Нови Искър / Кремиковци,NaN,177.0,177,142,5,4,4,6002209,1,1,1,a044af65-423a-4ce7-9fd1-094c343281f2,6.001423e+06,"MULTIPOLYGON (((23.46077 42.79646, 23.4605 42....",rudnik kremikovtsi 2,kremikovtsi
16,53,Южен парк част 3,Триадица,637.0,11181.0,11818,9454,315,270,236,731978,430,369,322,a4daef31-b41d-4c18-9666-4c594e728a0e,7.318795e+05,"MULTIPOLYGON (((23.30648 42.65691, 23.30648 42...",yuzhen park chast 3,yuzhen park
18,135,"ж.к. Надежда 3, ж.к. Връбница 1Б",Надежда / Връбница,267738.0,10824.0,278562,222850,7428,6367,5571,424525,17497,14998,13123,1b768ad0-25d7-4813-ad24-fd8cdc3bfe5f,4.244735e+05,"MULTIPOLYGON (((23.29632 42.73228, 23.29607 42...","nadezhda 3, vrabnitsa 1b",vrabnitsa 1
23,57,кв. Хладилника,Лозенец,262528.0,1682.0,264210,211368,7046,6039,5284,181424,38837,33287,29125,9c3d1e3f-aa1d-42d7-817c-50f5556a23a6,1.813986e+05,"MULTIPOLYGON (((23.31649 42.6593, 23.31375 42....",hladilnika,hladilnika
32,130,кв. Кръстова вада - изток,Лозенец,146761.0,30394.0,177155,141724,4724,4049,3543,589343,8016,6870,6012,1ff6154b-187d-4432-b8a7-1a47c20e357a,5.892638e+05,"MULTIPOLYGON (((23.32148 42.6567, 23.32147 42....",krastova vada - iztok,krastova vada
35,63,ЦГЧ Зона Г8 част Триадица,Триадица,276037.0,4650.0,280687,224550,7485,6416,5614,273390,27378,23468,20535,12c92d74-773d-46b3-af50-46413fb35149,2.733512e+05,"MULTIPOLYGON (((23.31897 42.689, 23.31805 42.6...",tsgch zona g8 chast triaditsa,NaN
38,66,ЦГЧ Зона А - юг,Средец,89126.0,1173.0,90299,72239,2408,2064,1806,260692,9237,7917,6928,d4c6c1e7-0f20-40f4-b1f2-b2740eadb6ec,2.606574e+05,"MULTIPOLYGON (((23.32353 42.69742, 23.32416 42...",tsgch zona a - yug,NaN
44,248,Борисова градина - Семинарията,Лозенец,NaN,2118.0,2118,1694,56,48,42,411006,136,117,102,2185c90d-6060-4e34-b203-5c4ad22cf6b8,4.109501e+05,"MULTIPOLYGON (((23.34175 42.67747, 23.34089 42...",borisova gradina - seminariyata,gradina
46,170,с. Г. и Д. Богров поле юг,Кремиковци,NaN,190.0,190,152,5,4,4,10519070,0,0,0,58e0ea7f-f5f4-47c1-adff-4752480edfa9,1.051766e+07,"MULTIPOLYGON (((23.49715 42.70708, 23.49714 42...",g. i d. bogrov pole yug,NaN
50,67,ЦГЧ Зони Б2 1 и 2,Възраждане / Триадица,77543.0,7390.0,84933,67946,2265,1941,1699,182083,12439,10660,9331,fdb1a3cd-83cf-457c-b733-cf6cfc4a5648,1.820592e+05,"MULTIPOLYGON (((23.32023 42.69805, 23.32172 42...",tsgch zoni b2 1 i 2,NaN
55,8,ЦГЧ Зона А - север,Средец / Оборище,27744.0,NaN,27744,22195,740,634,555,98238,7533,6454,5650,e5cda8d8-50bd-46bc-8486-f432802e9587,9.822538e+04,"MULTIPOLYGON (((23.33011 42.69626, 23.33008 42...",tsgch zona a - sever,NaN
61,69,Бизнес зона бул. Източна тангента - Враждебна,Подуене / Кремиковци,NaN,1355.0,1355,1084,36,31,27,830297,43,37,33,0a0cf792-ebbd-47e9-9c64-3f00ef224566,8.301731e+05,"MULTIPOLYGON (((23.39776 42.71574, 23.39882 42...",biznes zona bul. iztochna tangenta - vrazhdebna,vrazhdebna
66,138,СПЗ Модерно предградие - разширение 2,Връбница,NaN,3889.0,3889,3111,104,89,78,379489,274,235,206,c2a46f00-cff3-44d9-a759-7512eae5e670,3.794379e+05,"MULTIPOLYGON (((23.2523 42.74075, 23.25219 42....",spz moderno predgradie - razshirenie 2,moderno predgradie
70,93,кв. Модерно предградие,Връбница,145807.0,128643.0,274450,219560,7319,6273,5489,1558705,4696,4024,3522,ff0887f1-f439-4d61-9069-2df02dc9f93b,1.558497e+06,"MULTIPOLYGON (((23.27642 42.73039, 23.27731 42...",moderno predgradie,moderno predgradie
74,17,ЦГЧ Зона Г8 - Средец,Средец,325861.0,2982.0,328843,263074,8769,7516,6577,305740,28681,24583,21512,e4917283-4c1f-4418-8225-d50bd2786f11,3.056905e+05,"MULTIPOLYGON (((23.33097 42.68641, 23.32069 42...",tsgch zona g8 - sredets,NaN
79,21,ж.к. Кръстова вада - запад,Триадица,227601.0,76734.0,304335,243468,8116,6956,6087,977158,8306,7119,6229,31978ee0-cc7f-41b6-9075-a4b45dd40b2c,9.770263e+05,"MULTIPOLYGON (((23.31297 42.65682, 23.31457 42...",krastova vada - zapad,krastova vada
80,22,ЦГЧ Зона Г8,Средец,364256.0,2622.0,366878,293502,9783,8386,7338,289595,33782,28958,25339,92af80f5-cdcd-4512-a2fb-b879e2bf28af,2.895552e+05,"MULTIPOLYGON (((23.32211 42.69475, 23.32219 42...",tsgch zona g8,NaN
83,95,ж.к. Обеля 1,Връбница,160414.0,16091.0,176505,141204,4707,4034,3530,410715,11461,9822,8595,f2ac7f1c-a034-41cd-9884-88b08dfc14af,4.106598e+05,"MULTIPOLYGON (((23.26518 42.74073, 23.26602 42...",obelya 1,obelya 1
92,24,"с. Волуяк, м. Влашка река",Връбница,NaN,NaN,0,0,0,0,0,1838104,0,0,0,5e31f942-ca2d-46c2-9837-d6a66ba7f856,1.837860e+06,"MULTIPOLYGON (((23.21166 42.77039, 23.21204 42...","voluyak, vlashka reka",NaN
94,34,"с. Волуяк, м. Полето 2",Връбница,NaN,NaN,0,0,0,0,0,357916,0,0,0,65c6a046-20ae-42b1-91d2-21341ef92aa7,3.578693e+05,"MULTIPOLYGON (((23.22649 42.78795, 23.2265 42....","voluyak, poleto 2",NaN
97,102,"с. Волуяк, м. Чучулица",Връбница,NaN,196.0,196,157,5,4,4,405355,12,10,10,a14e8ca6-7277-4fa0-9c6a-320cd0f20548,4.053338e+05,"MULTIPOLYGON (((23.27768 42.74931, 23.27767 42...","voluyak, chuchulitsa",NaN
98,103,НПЗ Кремиковци,Кремиковци,NaN,8859.0,8859,7087,236,202,177,12148147,19,17,15,f17e671c-1dd6-43c0-adf0-486f195b8c01,1.214652e+07,"MULTIPOLYGON (((23.52371 42.76172, 23.52818 42...",npz kremikovtsi,kremikovtsi
99,498,Хидропарк Искър - дефилето,Нови Искър / Кремиковци,NaN,63.0,63,50,2,1,1,822607,2,1,1,a99e021e-ca3b-4711-9a5b-2c748c646ddf,8.225030e+05,"MULTIPOLYGON (((23.36569 42.84154, 23.36569 42...",hidropark iskar - defileto,NaN
100,39,ж.к. Стрелбище,Триадица,784504.0,10971.0,795475,636380,21213,18182,15910,741025,28627,24536,21470,2b3899cf-11b1-435b-9f68-d57093d85378,7.409231e+05,"MULTIPOLYGON (((23.30381 42.67469, 23.30384 42...",strelbishte,strelbishte
106,29,Софийска планина (западна Стара планина) 1,Нови Искър / Кремиковци,NaN,425.0,425,340,11,10,9,31050089,0,0,0,2ceea6a9-863f-4e5d-bef2-305476577bc4,3.104627e+07,"MULTIPOLYGON (((23.28168 42.89617, 23.28176 42...",sofiyska planina (zapadna stara planina) 1,NaN
109,32,к-с Медицинска академия,Триадица,39891.0,8224.0,48115,38492,1283,1100,962,553130,2320,1989,1739,8731b130-db87-4826-8261-525f1d8ec373,5.530578e+05,"MULTIPOLYGON (((23.31041 42.687, 23.31495 42.6...",k-s meditsinska akademiya,meditsinska akademiya
114,44,ЦГЧ Зона А - изток,Средец / Оборище,52306.0,880.0,53186,42549,1418,1216,1064,203583,6965,5973,5226,c10b2451-b34c-4b10-ba7e-14766c176093,2.035554e+05,"MULTIPOLYGON (((23.33443 42.69334, 23.33438 42...",tsgch zona a - iztok,iztok
120,178,"Бенковски, м. Могилата",Кремиковци,NaN,NaN,0,0,0,0,0,71177,0,0,0,627df240-12b1-4d52-afb3-d2cfb19b84fd,7.116780e+04,"MULTIPOLYGON (((23.37704 42.73455, 23.37684 42...","benkovski, mogilata",benkovski
123,125,"кв. Враждебна, Бизнес зона м. Прогоно",Кремиковци,NaN,1967.0,1967,1574,52,45,39,828555,63,54,47,726017e9-05d7-4c6a-bdbc-dba52f73f3f6,8.284676e+05,"MULTIPOLYGON (((23.44989 42.70756, 23.44995 42...","vrazhdebna, biznes zona progono",vrazhdebna
128,119,"с. Мрамор, м. Кръста",Връбница,NaN,NaN,0,0,0,0,0,374816,0,0,0,9716f2d2-79d5-4574-b09c-936d4aca34b1,3.747601e+05,"MULTIPOLYGON (((23.27243 42.7784, 23.27254 42....","mramor, krasta",NaN
133,181,НДК - площад България,Триадица,20286.0,71.0,20357,16286,543,465,407,266802,2035,1743,1525,2b16abc3-8def-4600-bb30-a9a8d0368dad,2.667663e+05,"MULTIPOLYGON (((23.31673 42.68184, 23.31581 42...",ndk - ploshtad balgariya,NaN
135,83,"кв. Враждебна, м. Локвата",Кремиковци,NaN,27.0,27,22,1,1,1,750101,1,1,1,28a6ac48-7faf-43fa-9221-e1b86a67a906,7.500004e+05,"MULTIPOLYGON (((23.39046 42.7308, 23.39062 42....","vrazhdebna, lokvata",vrazhdebna
137,85,Парк Левски Г - север,Кремиковци,NaN,NaN,0,0,0,0,0,706248,0,0,0,895b9fe0-d949-4163-bc77-787e82ccdee7,7.061527e+05,"MULTIPOLYGON (((23.39077 42.7203, 23.38996 42....",park levski g - sever,levski g
140,86,с. Яна,Кремиковци,2679.0,55432.0,58111,46489,1550,1328,1162,956137,1621,1389,1215,9612f7bb-0679-4d6c-9757-6fa9d2d9e24a,9.560095e+05,"MULTIPOLYGON (((23.56615 42.73661, 23.56618 42...",yana,NaN
141,87,Парк кв. Враждебна - север,Нови Искър / Кремиковци,99.0,150.0,249,199,7,6,5,365512,19,16,14,3ee08418-b28f-4394-ac14-b851fbc113e6,3.654626e+05,"MULTIPOLYGON (((23.41973 42.71641, 23.41975 42...",park vrazhdebna - sever,vrazhdebna
146,109,с. Мрамор и ПСЗ,Връбница,16378.0,111395.0,127773,102218,3407,2921,2555,3254612,1047,897,785,b46f8825-07df-4c3a-9366-5540f0354a7f,3.254186e+06,"MULTIPOLYGON (((23.28003 42.79168, 23.28102 42...",mramor i psz,NaN
149,129,"с. Волуяк, м. Локва",Връбница,NaN,NaN,0,0,0,0,0,702130,0,0,0,bf7a227a-aa80-42f8-9c80-5ea2e37de188,7.020441e+05,"MULTIPOLYGON (((23.27242 42.74865, 23.26953 42...","voluyak, lokva",NaN
151,106,"с. Волуяк, м. Падината",Връбница,NaN,NaN,0,0,0,0,0,2452212,0,0,0,c54cb41b-689d-48a8-bb6f-3fa1b0fdcdda,2.451881e+06,"MULTIPOLYGON (((23.25683 42.7695, 23.25778 42....","voluyak, padinata",NaN
152,107,"с. Волуяк, м. Църна бара",Връбница,NaN,NaN,0,0,0,0,0,2968196,0,0,0,c81cd5f5-e541-42d3-890b-dc3eadbf068f,2.967802e+06,"MULTIPOLYGON (((23.23686 42.7896, 23.23758 42....","voluyak, tsarna bara",NaN
162,184,ЦГЧ Зона Г12 - юг,Средец,135028.0,3711.0,138739,110991,3700,3171,2775,177898,20798,17825,15599,20ecd385-c4a9-4229-958a-0c1e46073127,1.778740e+05,"MULTIPOLYGON (((23.34444 42.69253, 23.34425 42...",tsgch zona g12 - yug,NaN
163,126,зем. земи Малашевци Герена,Кремиковци,NaN,NaN,0,0,0,0,0,762996,0,0,0,ac49c8f5-7f0a-454d-a09f-2097bb09b748,7.628943e+05,"MULTIPOLYGON (((23.38359 42.72501, 23.38512 42...",ze zemi malashevtsi gerena,malashevtsi
166,127,"с. Д. Богров, м. Бресто",Кремиковци,NaN,1383.0,1383,1106,37,32,28,4251625,9,8,7,6cc066cf-9095-4be4-8bba-5f809e58fcdd,4.251080e+06,"MULTIPOLYGON (((23.52841 42.72497, 23.52786 42...","d. bogrov, bresto",NaN
167,128,"с. Д.Богров, м. Ормана",Кремиковци,NaN,135.0,135,108,4,3,3,634258,6,5,5,e7ad5cf4-2afe-43dc-85a3-929f6afa3767,6.341900e+05,"MULTIPOLYGON (((23.49508 42.70714, 23.49455 42...","d.bogrov, ormana",NaN
171,134,"ж.к. Надежда 3, ж.к. Връбница 1А",Надежда / Връбница,224164.0,9337.0,233501,186801,6227,5337,4670,583022,10681,9154,8010,7cfac841-f8fe-4b4b-8679-1703d4b26213,5.829450e+05,"MULTIPOLYGON (((23.29287 42.73539, 23.28621 42...","nadezhda 3, vrabnitsa 1a",vrabnitsa 1
174,140,Парк - Борисова градина - разш. Кръстова вада,Лозенец,13044.0,12525.0,25569,20455,682,584,511,1155424,590,505,442,83f4c704-aa7a-4832-b82c-19ada7e4c2b7,1.155268e+06,"MULTIPOLYGON (((23.32798 42.65658, 23.32803 42...",park - borisova gradina - razsh. krastova vada,krastova vada
179,147,м. Враждебна - юг,Подуене / Кремиковци,1104.0,5115.0,6219,4975,166,142,124,628473,264,226,197,55289a3e-b9ca-4e4b-9ad5-faed880c99e3,6.284136e+05,"MULTIPOLYGON (((23.41946 42.70722, 23.4194 42....",vrazhdebna - yug,vrazhdebna
180,148,м. Япаджа,Нови Искър / Кремиковци,397.0,7506.0,7903,6322,211,181,158,354238,596,511,446,dcb79bac-9b08-4c85-8e81-2c494685cd4f,3.541899e+05,"MULTIPOLYGON (((23.43171 42.71322, 23.43176 42...",yapadzha,NaN
183,151,Озеленяване трансп. възел Северна - източна та...,Кремиковци,NaN,NaN,0,0,0,0,0,240348,0,0,0,9fd26410-dea5-4ce9-98d7-8d0b076a04ce,2.403162e+05,"MULTIPOLYGON (((23.39648 42.72028, 23.39674 42...",ozelenyavane transp. vazel severna - iztochna ...,NaN
189,155,ж.к. Манастирски ливади - изток,Триадица,519236.0,39751.0,558987,447190,14906,12777,11180,1829916,8146,6982,6110,0794cf67-4784-4216-9310-094fa57e3113,1.829678e+06,"MULTIPOLYGON (((23.30278 42.65776, 23.30267 42...",manastirski livadi - iztok,manastirski livadi
195,161,зем. земи р-н Кремиковци,Кремиковци,1088.0,529.0,1617,1294,43,37,32,35857639,1,1,1,bf7cb9bb-4ff1-4049-a417-e3be9d497436,3.585287e+07,"MULTIPOLYGON (((23.51277 42.77589, 23.51288 42...",ze zemi r-n kremikovtsi,kremikovtsi
196,162,Софийска планина (западна Стара планина) 2,Нови Искър / Кремиковци,NaN,4161.0,4161,3329,111,95,83,167093557,1,1,0,a2a04928-8e19-48ef-9f30-031dcbf5db87,1.670722e+08,"MULTIPOLYGON (((23.41042 42.81529, 23.41042 42...",sofiyska planina (zapadna stara planina) 2,NaN
199,175,м. Богровски песоци,Кремиковци,NaN,NaN,0,0,0,0,0,473129,0,0,0,9219d0d4-ae08-4a39-9dcd-b25b6f7f4ff8,4.730622e+05,"MULTIPOLYGON (((23.4532 42.71065, 23.45362 42....",bogrovski pesotsi,NaN
200,176,кв. Витоша - Лозенец,Лозенец,702017.0,99113.0,801130,640904,21363,18312,16023,1877999,11375,9751,8532,3ed3b94a-0eae-4729-9baf-e0687b9087be,1.877743e+06,"MULTIPOLYGON (((23.33644 42.65705, 23.3363 42....",vitosha - lozenets,lozenets
203,185,с. Ботунец,Кремиковци,143856.0,36589.0,180445,144356,4812,4124,3609,1535867,3133,2685,2350,a8472934-0635-4a08-bfbe-f996905f852a,1.535663e+06,"MULTIPOLYGON (((23.51285 42.74356, 23.51636 42...",botunets,botunets
207,189,"ж.к. Надежда 4, ж.к. Връбница 2Б",Надежда / Връбница,190865.0,3935.0,194800,155840,5195,4453,3896,339165,15317,13129,11487,2bd7d213-4d36-4a14-b215-3974fd66ee40,3.391132e+05,"MULTIPOLYGON (((23.29812 42.73829, 23.29287 42...","nadezhda 4, vrabnitsa 2b",vrabnitsa 2
210,192,м. Батарея,Кремиковци,1019.0,7448.0,8467,6774,226,194,169,196551,1150,987,860,58da63ea-bc56-4327-a646-065db8b4ca94,1.965251e+05,"MULTIPOLYGON (((23.43087 42.70903, 23.4308 42....",batareya,NaN
223,213,м. Лозенец част 3,Лозенец,589497.0,22625.0,612122,489698,16323,13991,12242,822255,19852,17015,14888,b64169eb-ce1a-48bb-8b7c-25f4c6beaaef,8.221547e+05,"MULTIPOLYGON (((23.33564 42.6825, 23.33569 42....",lozenets chast 3,lozenets
234,368,"с. Мрамор, м. Келказа",Връбница,NaN,250.0,250,200,7,6,5,572525,12,10,9,16a6873c-03df-4093-949a-14275bee9582,5.724476e+05,"MULTIPOLYGON (((23.27542 42.77251, 23.27531 42...","mramor, kelkaza",NaN
248,232,"кв. Челопечене, м. Дево мост",Кремиковци,NaN,1272.0,1272,1018,34,29,25,1023093,33,28,24,652e5bea-88c1-4b55-8769-7c6b6a7c8e03,1.022960e+06,"MULTIPOLYGON (((23.48452 42.74838, 23.4915 42....","chelopechene, devo most",chelopechene
253,229,Борисова градина - север,Средец,NaN,900.0,900,720,24,21,18,956826,25,22,19,a7e29b97-8be2-46d0-8220-58c98d8e891a,9.567105e+05,"MULTIPOLYGON (((23.33396 42.68854, 23.33613 42...",borisova gradina - sever,gradina
258,240,ж.к. Гоце Делчев,Триадица,750122.0,4877.0,754999,603999,20133,17257,15100,1003641,20060,17194,15045,b7a21e3f-ab0f-4f91-b58e-9cbeaf6dfde5,1.003499e+06,"MULTIPOLYGON (((23.30283 42.65783, 23.30278 42...",gotse delchev,gotse delchev
259,241,3-та извънградска част,Средец,345377.0,9454.0,354831,283865,9462,8110,7097,453355,20871,17889,15654,6f4a5824-9a88-453b-b871-d5985023a62c,4.532802e+05,"MULTIPOLYGON (((23.34764 42.6835, 23.34753 42....",3-ta izvangradska chast,NaN
271,250,ЦГЧ Зони Г10 и част от А,Средец,257747.0,2693.0,260440,208352,6945,5953,5209,301197,23058,19764,17294,50c5651a-dc40-4dc9-bffe-f78063adb99f,3.011570e+05,"MULTIPOLYGON (((23.33438 42.69312, 23.33411 42...",tsgch zoni g10 i chast ot a,NaN
276,254,"с. Яна, м. Садината",Кремиковци,NaN,NaN,0,0,0,0,0,1050681,0,0,0,52ee7c4a-155f-4743-a477-37955eb6994f,1.050535e+06,"MULTIPOLYGON (((23.58702 42.72398, 23.58539 42...","yana, sadinata",NaN
278,256,"с. Волуяк, м. Раздолци",Връбница,NaN,341.0,341,273,9,8,7,603902,15,13,12,34584c93-1dc2-41e2-b3d1-701348a6a5d1,6.038232e+05,"MULTIPOLYGON (((23.20848 42.76782, 23.20848 42...","voluyak, razdoltsi",NaN
286,264,Рудник Кремиковци,Кремиковци,NaN,NaN,0,0,0,0,0,2915579,0,0,0,dcb7cb07-7c1b-4d67-bace-c13425800d66,2.915197e+06,"MULTIPOLYGON (((23.48417 42.789, 23.48505 42.7...",rudnik kremikovtsi,kremikovtsi
294,275,"Челопечене, м. Ленищата",Кремиковци,NaN,NaN,0,0,0,0,0,690888,0,0,0,d124247b-0ab6-411a-aca5-1134b450e520,6.907956e+05,"MULTIPOLYGON (((23.45352 42.72573, 23.45396 42...","chelopechene, lenishtata",chelopechene
300,284,м. Зоопарк,Лозенец,7588.0,646.0,8234,6587,220,188,165,346251,635,543,477,8b5841b8-3279-496a-8223-db1ed1951cc3,3.462048e+05,"MULTIPOLYGON (((23.33679 42.66042, 23.33673 42...",zoopark,zoopark
306,293,Борисова градина - Погребите част 1,Лозенец,NaN,1384.0,1384,1107,37,32,28,785529,47,41,36,9e1e76d6-c6f8-48e5-af3d-c2b5e76adfbe,7.854225e+05,"MULTIPOLYGON (((23.33766 42.67098, 23.3377 42....",borisova gradina - pogrebite chast 1,gradina
309,296,НПЗ Хладилника,Лозенец,64481.0,2809.0,67290,53832,1794,1538,1346,1056877,1697,1455,1274,8228af3d-06fc-4fac-9f71-2abec80a91c9,1.056735e+06,"MULTIPOLYGON (((23.32802 42.66109, 23.32777 42...",npz hladilnika,pz hladilnika
312,299,кв. Враждебна,Кремиковци,40724.0,191525.0,232249,185799,6193,5309,4645,1797219,3446,2954,2585,fd36729d-265c-4797-9df9-1fac288cd3a2,1.796968e+06,"MULTIPOLYGON (((23.40965 42.7167, 23.41462 42....",vrazhdebna,vrazhdebna
315,302,Южен парк част 2,Триадица,NaN,NaN,0,0,0,0,0,444951,0,0,0,91b06e42-10a8-419b-b0df-f8f66273f1d0,4.448911e+05,"MULTIPOLYGON (((23.32098 42.68201, 23.32123 42...",yuzhen park chast 2,yuzhen park
318,305,Южен парк,Триадица,11256.0,2446.0,13702,10962,365,313,274,1284315,284,244,213,bb808878-ad34-4b7d-82bb-db6391bd07dc,1.284141e+06,"MULTIPOLYGON (((23.31039 42.6713, 23.31055 42....",yuzhen park,yuzhen park
321,308,м. Лозенец част 2 и 3 - юг,Лозенец,572145.0,15615.0,587760,470208,15674,13435,11755,871420,17987,15417,13489,bc51b964-dc56-4193-8e43-278f340b225d,8.713055e+05,"MULTIPOLYGON (((23.33517 42.67181, 23.33475 42...",lozenets chast 2 i 3 - yug,lozenets
322,309,ж.к. Иван Вазов,Триадица,375254.0,2928.0,378182,302546,10085,8644,7564,537882,18749,16070,14063,0edeb469-9517-416f-93da-9dbf6eabd694,5.378094e+05,"MULTIPOLYGON (((23.31326 42.68161, 23.31553 42...",ivan vazov,ivan vazov
324,311,м. Лозенец част 2 - север,Лозенец,164198.0,13071.0,177269,141815,4727,4052,3545,382824,12348,10584,9260,089b2868-5663-415b-8529-4bbe0d6459b1,3.827690e+05,"MULTIPOLYGON (((23.33373 42.67633, 23.32826 42...",lozenets chast 2 - sever,lozenets
335,322,ЦГЧ Зона Г11 - изток,Средец,121174.0,331.0,121505,97204,3240,2777,2430,83809,38659,33135,28994,a9f9a12d-0f80-4ebf-9ee8-8277423fecb3,8.379731e+04,"MULTIPOLYGON (((23.33396 42.68854, 23.33097 42...",tsgch zona g11 - iztok,iztok
349,336,Хвостохранилище Богров - Лъката,Кремиковци,NaN,NaN,0,0,0,0,0,1767527,0,0,0,d0a49092-0167-435b-af32-6a0a06092920,1.767309e+06,"MULTIPOLYGON (((23.5154 42.70116, 23.51546 42....",hvostohranilishte bogrov - lakata,NaN
352,340,Хидропарк Искър - част Летище север,Слатина / Кремиковци,NaN,NaN,0,0,0,0,0,1332301,0,0,0,cbcec58c-3587-4cdb-a0f2-afe04e514709,1.332119e+06,"MULTIPOLYGON (((23.42398 42.70938, 23.42419 42...",hidropark iskar - chast letishte sever,NaN
359,347,м. Хан Богров - ПЗ,Кремиковци,NaN,1116.0,1116,893,30,26,22,1853186,16,14,12,1099ce7f-c1d6-4fa4-8762-217e07932d06,1.852918e+06,"MULTIPOLYGON (((23.52229 42.71377, 23.52238 42...",han bogrov - pz,NaN
365,350,с. Долни Богров,Кремиковци,3516.0,71361.0,74877,59902,1997,1711,1498,1256521,1589,1362,1192,2dfa4e90-f499-4d2d-b97e-8bdac0ea014f,1.256357e+06,"MULTIPOLYGON (((23.49435 42.70629, 23.49514 42...",dolni bogrov,NaN
376,370,с. Горни Богров,Кремиковци,5802.0,63144.0,68946,55157,1839,1576,1379,1296497,1418,1216,1064,ca2b815b-6ace-4270-9ee5-d8799996701e,1.296325e+06,"MULTIPOLYGON (((23.54373 42.72445, 23.5444 42....",gorni bogrov,NaN
381,376,м. Голямата локва,Нови Искър / Кремиковци,538.0,5122.0,5660,4528,151,129,113,1752703,86,74,64,64b98a91-253d-412b-b155-590f65eddcc1,1.752443e+06,"MULTIPOLYGON (((23.44759 42.72186, 23.44748 42...",golyamata lokva,NaN
384,379,Северен парк - Бакърена фабрика,Връбница,NaN,1494.0,1494,1195,40,34,30,1353849,30,25,22,759a22b9-2910-4112-ba0a-4a5f88df4abd,1.353667e+06,"MULTIPOLYGON (((23.28554 42.74201, 23.28712 42...",severen park - bakarena fabrika,NaN
388,389,Хвостохранилище Челопечене,Кремиковци,NaN,NaN,0,0,0,0,0,1830180,0,0,0,dd3e15dd-1270-442b-98a0-827236f67969,1.829893e+06,"MULTIPOLYGON (((23.49692 42.72912, 23.49714 42...",hvostohranilishte chelopechene,chelopechene
395,418,ж.к. Обеля 2,Връбница,378600.0,413.0,379013,303210,10107,8663,7580,644285,15687,13446,11765,3745f63b-ccbe-4dac-9a12-4bfe5a3ced68,6.441998e+05,"MULTIPOLYGON (((23.28223 42.74504, 23.28396 42...",obelya 2,obelya 2

In [38]:
gdf = gpd.GeoDataFrame(merge, geometry='geometry', crs=districts.crs)

gdf[gdf['location'].str.contains('Sofia, Tsentar')].drop_duplicates(subset='location_clean')

,url,ad_id,listing_type,location,price_eur,area_sqm,price_per_sqm_eur,floor,central_heating,gas,...,ppl_40kvm,area_ge,dens30_ppl_kvkm,dens35_ppl_kvkm,dens40_ppl_kvkm,id,area_kv_m,geometry,regname_clean,regname_clean_2
22075,https://imoti.info/en/properties/91976678-for-...,91976678,Studio,"Sofia, Tsentar",175 000,60,"2 916,67",5th,YES,-,...,48.0,449941.0,142.0,122.0,107.0,57f8648b-7a9c-4b52-9c12-0a393c7afa25,449880.12,"MULTIPOLYGON (((23.19482 42.67822, 23.19484 42...",meditsinski tsentar suhodol,tsentar