In [2]:
import pandas as pd
import geopandas as gpd

# Gets the folder directory where urban data is located to avoid duplication
folder = r'D:\Data Analysis\5_Projects\sofia_housing_districts_analysis\data\sofia_data\urbandata_sofia_bg'

# Reads file with district boundaries
district_boundaries = gpd.read_file(folder + r'\natovarv_sasht_polojenie_kk_072020_26_sofpl_20201118.geojson')

# Gets unique districts
district_boundaries['rajon'].unique()

districts = district_boundaries['rajon'].unique()

split_districts = set()
for district in districts:
    if isinstance(district, str):
        split_district = district.split(' / ')
        split_districts.add(split_district[0].strip())

    if len(split_district) == 2:
        split_districts.add(split_district[1].strip())

# A set of unique Sofia Municipality districts in cyrillic
split_districts

{'Банкя',
 'Витоша',
 'Връбница',
 'Възраждане',
 'Изгрев',
 'Илинден',
 'Искър',
 'Красна поляна',
 'Красно село',
 'Кремиковци',
 'Лозенец',
 'Люлин',
 'Младост',
 'Надежда',
 'Нови Искър',
 'Оборище',
 'Овча Купел',
 'Панчарево',
 'Подуене',
 'Сердика',
 'Слатина',
 'Средец',
 'Студентска',
 'Триадица'}

In [27]:
public_transport_accessibility = gpd.read_file(folder + r'\dostup_mgt_all_400_600_800m_overlap_20210300.geojson')

public_transport_accessibility[public_transport_accessibility['name_'].str.contains('ЛЮЛИН')]

,object_id,objectid,facilityid,name_,frombreak,tobreak,id,area_kv_m,geometry
62,4355,48875.0,5854.0,ТЪРГОВСКИ Ц-Р ЛЮЛИН : 400 - 600,400.0,600.0,f8f08cf3-eafe-4a7f-a785-e591bb089353,402896.00,"MULTIPOLYGON (((23.25436 42.72296, 23.25439 42..."
204,450,44970.0,3650.0,БЛ. 135 Ж.К. ЛЮЛИН-10 : 600 - 800,600.0,800.0,d3a06829-423f-460d-84a4-197ac34e60c9,443480.87,"MULTIPOLYGON (((23.28035 42.72152, 23.28032 42..."
205,501,45021.0,3667.0,БЛ. 350 Ж.К. ЛЮЛИН-3 : 600 - 800,600.0,800.0,bb0aaf82-ddae-4f61-a895-9cd2fdb42255,465616.68,"MULTIPOLYGON (((23.24728 42.73139, 23.2485 42...."
224,447,44967.0,3649.0,БЛ. 135 Ж.К. ЛЮЛИН-10 : 600 - 800,600.0,800.0,59affa03-7747-4027-a8ac-c7430357f47c,457151.55,"MULTIPOLYGON (((23.28078 42.72138, 23.28142 42..."
231,504,45024.0,3668.0,БЛ. 350 Ж.К. ЛЮЛИН-3 : 600 - 800,600.0,800.0,01574fc3-ce75-4a48-bd24-28742cbb08d0,482547.04,"MULTIPOLYGON (((23.24724 42.73133, 23.24841 42..."
...,...,...,...,...,...,...,...,...,...
8269,8138,52658.0,6224.0,БЛ. 539 Ж.К.ЛЮЛИН-5 : 0 - 400,0.0,400.0,dd6e97d6-e61b-48dc-8cf6-4a539f7643d5,173387.74,"MULTIPOLYGON (((23.24121 42.71434, 23.24148 42..."
8277,8163,52683.0,4577.0,Ж.К. ЛЮЛИН 8 : 0 - 400,0.0,400.0,d552f822-cf85-459b-a28c-a2e43b79e320,269898.02,"MULTIPOLYGON (((23.26131 42.72581, 23.26133 42..."
8511,8498,53018.0,6344.0,БЛ. 350 Ж.К. ЛЮЛИН-3 : 0 - 400,0.0,400.0,dec89f93-9fd4-46fd-9ae6-1cb4f784f8d5,288304.01,"MULTIPOLYGON (((23.24575 42.72873, 23.24573 42..."
8534,8517,53037.0,4458.0,ХИТ МАРКЕТ ЛЮЛИН : 0 - 400,0.0,400.0,7a37a84b-53c1-47c4-849c-2264c96c2111,83726.40,"MULTIPOLYGON (((23.26954 42.73417, 23.26945 42..."
8535,8518,53038.0,4457.0,ХИТ МАРКЕТ ЛЮЛИН : 0 - 400,0.0,400.0,a7ab532c-2504-47a0-ba75-f22e57ccf975,110667.54,"MULTIPOLYGON (((23.26683 42.7308, 23.2664 42.7..."

In [31]:
public_transport_accessibility.tail(10).explore()

In [22]:
schools_accessibility = gpd.read_file(folder + r'\uchilishta_points_26_sofpr_20180808.geojson')

# displayed kod_rayon for further mapping in SCHOOLS ACCESSIBILITY
#schools_accessibility.drop_duplicates(subset='kod_rayon').sort_values('kod_rayon')

schools_accessibility.head()

,id,object_nam,object_nom,kod_rayon,adres,finansiran,type,detaili,zabelezhka,br_paralel,kodadmin,geometry
0,1,Национално училище за танцово изкуство,NaN,07,бул. Шипченски проход №48,1,4,http://89.252.196.217/Schools/search,NaN,0.0,2902301,MULTIPOINT ((23.36594 42.67788))
1,2,22 СОУ Георги С. Раковски,22.0,10,бул. Витоша №132,2,3,http://89.252.196.217/Schools/search,NaN,55.0,2224022,MULTIPOINT ((23.31459 42.68476))
2,3,"1-во помощно училище ""ПРОФ. ДПН Г. АНГУШЕВ"" (Ц...",NaN,12,бул. Тодор Александров №175,1,6,http://89.252.196.217/Schools/search,Център за специална образователна подкрепа (ЦСОП,0.0,0,MULTIPOINT ((23.29248 42.70397))
3,4,Национална природо-математическа гимназия Акад...,NaN,09,"ж.к. Лозенец, ул. Бигла №52",1,4,http://89.252.196.217/Schools/search,NaN,40.0,2211304,MULTIPOINT ((23.33011 42.67053))
4,5,21 СОУ Христо Ботев,21.0,09,"ж.к. Лозенец, ул. Люботрън №12",2,3,http://89.252.196.217/Schools/search,NaN,33.0,2211021,MULTIPOINT ((23.31546 42.66941))

In [23]:
kindergartens_accessibility = gpd.read_file(folder + r'\dg_points_26_sofpr_20180808.geojson')

#kindergartens_accessibility.drop_duplicates(subset='kod_rayon').sort_values('kod_rayon')

kindergartens_accessibility.head()

,id,object_nam,object_nom,kod_rayon,adres,finansiran,detaili,status,type,zabelezhka,chek,geometry
0,1,"ДГ №133 ""Зорница""",133,08,"ул. ""Еужен Поатие"" №1",2,https://www.sofia.bg/documents/20182/887150/DG...,NaN,1,NaN,1,MULTIPOINT ((23.36022 42.6701))
1,2,"ДГ №29 ""Слънце""",29,08,"ул.""Тодор Стоянов"" №18",2,https://www.sofia.bg/documents/20182/887150/DG...,NaN,4,NaN,1,MULTIPOINT ((23.35968 42.67052))
2,3,"ДГ №49 ""Радост""",49,08,"ул. ""Св. Пимен Зографски"" №5",2,https://www.sofia.bg/documents/20182/887150/DG...,NaN,4,NaN,1,MULTIPOINT ((23.35186 42.6653))
3,4,ДГ №121,121,21,"гр. Нови Искър, кв. Кумарица, ул. ""Искърско де...",2,https://www.sofia.bg/documents/20182/887183/DG...,NaN,4,NaN,1,MULTIPOINT ((23.33946 42.79707))
4,5,ДГ №121 - филиал с. Доброславци,121,21,"с.Доброславци, ул. ""Площад Мегдана"" №1",2,https://www.sofia.bg/documents/20182/887183/DG...,NaN,4,"има данни за съществуващ филиал, но няма данни...",2,MULTIPOINT ((23.28315 42.82149))

In [6]:
healthcare_accessibility = gpd.read_file(folder + r'\dkc_obsl_naselenie_grao_25_sofpl_20210100.geojson')

healthcare_accessibility.columns

Index(['object_id', 'coeff', 'percent_serv', 'percent_unserv', 'tot_ppl_count',
       'serv_ppl', 'unserv_ppl', 'id', 'area_kv_m', 'geometry'],
      dtype='str')

In [25]:
parking_accessibility = gpd.read_file(folder + r'\parkomesta_25_cgm_20200900.geojson') 

parking_accessibility.head()

,id,objectid,park_txt,zona,mestopoloz,georef_201,vid_txt_20,zabelezhka,obekt,dogovor_sr,dogovor_nu,type,bezplatni_,podzona_nu,sf_rayon,geometry
0,1,1.0,Надлъжн,Зелена зона,ул. Юри Венелин,2009,Зона,-,-,-,-,-,-,-,-,MULTIPOINT ((23.33186 42.68848))
1,2,2.0,Надлъжн,Зелена зона,ул. Юри Венелин,2009,Зона,-,-,-,-,-,-,-,-,MULTIPOINT ((23.33192 42.68844))
2,3,3.0,Косо,Зелена зона,ул. Юри Венелин,2009,Зона,-,-,-,-,-,-,-,-,MULTIPOINT ((23.33179 42.68859))
3,4,4.0,Косо,Зелена зона,ул. Юри Венелин,2009,Зона,-,-,-,-,-,-,-,-,MULTIPOINT ((23.33182 42.68858))
4,5,5.0,Косо,Зелена зона,ул. Юри Венелин,2009,Зона,-,-,-,-,-,-,-,-,MULTIPOINT ((23.33185 42.68856))

In [20]:
parks_accessibility = gpd.read_file(folder + r'\parkove_400_800_1200_2000m_25_sofpr_20190000.geojson')

parks_accessibility.sort_values('name_').head(8).explore()